from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


@dataclass
class PpDij:
    """Hamiltonian pseudo coefficients as defined in the Vanderbilt paper (PRB
    1990).

    If the pseudopotential is a PAW data set, they must contain the
    kinetic energy difference as well. !!CHECK!! a better/more accurate
    definition for these would be useful.
    """

    class Meta:
        name = "PP_DIJ"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    columns: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    size: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    type_value: Optional[str] = field(
        default=None,
        metadata={
            "name": "type",
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class PpInfo:
    """
    For human-readable data (ignored by QE).
    """

    class Meta:
        name = "PP_INFO"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


class UpfDataType(Enum):
    CHARACTER = "character"
    LOGICAL = "logical"
    INTEGER = "integer"
    REAL = "real"
    COMPLEX = "complex"


class UpfLogical(Enum):
    TRUE = ".true."
    T = "T"
    FALSE = ".false."
    F = "F"


class UpfPseudotype(Enum):
    """
    :cvar NC: norm-conserving
    :cvar SL: norm-conserving (semi-local form)
    :cvar US: Vanderbilt's ultrasoft
    :cvar PAW: Projector-Augmented Wave
    :cvar VALUE_1_R: Coulombian 1/r potential
    """

    NC = "NC"
    SL = "SL"
    US = "US"
    PAW = "PAW"
    VALUE_1_R = "1/r"


class UpfRelativisticType(Enum):
    """
    :cvar NO: non-relativistic calculation
    :cvar SCALAR: scalar-relativistic calculation
    :cvar FULL: full-relativistic calculation
    """

    NO = "no"
    SCALAR = "scalar"
    FULL = "full"


@dataclass
class PpHeader:
    """
    Machine-readable minimal data on the pseudopotential.

    :ivar element: Element symbol
    :ivar generated: Software used to generate the pseudopotential
    :ivar author: Author of pseudopotential
    :ivar date: Generation date
    :ivar comment:
    :ivar pseudo_type: Pseudopotential type (not used by the software,
        human-readable alias)
    :ivar relativistic: Level of relativistic formalism used in atomic
        calculation
    :ivar is_ultrasoft: True if pseudopotential is ultrasoft or PAW,
        i.e. if it has augmentation/compensation charge
    :ivar is_paw: True if pseudopotential is actually a PAW dataset
    :ivar is_coulomb: True if pseudopotential is a Coulombian 1/r
        potential
    :ivar has_so: True if spin-orbit information is present. In this
        case, the PP_SPIN_ORB section must be present.
    :ivar has_gipaw: True if additional information for GIPAW
        reconstruction is present. In this case, the PP_GIPAW section
        must be present.
    :ivar core_correction: True if the pseudopotential contains
        pseudized core charge for non-linear core. In this case, the
        PP_NLCC section must be present.
    :ivar functional: Short-name for the DFT functional used. It can
        either be an alias (such as PBE, LDA) or specify in order:
        functional for exchange, functional for corellation, gradient
        correction for exchange, gradient correction for corellation.
        E.g. PBE is 'SLA PW PBX PBC'. The list of short-names understood
        by QE is listed at the beginning of file Modules/functional.f90
        in its source tree.
    :ivar z_valence: Valence charge (atomic number - core charge) in
        units of abs(electron charge). This will usually coincide with
        the number of valence electrons. If the pseudopotential has been
        generated with a charged configuration, z_valence will *not* be
        affected, but the sum of the occupations will not match this
        value.
    :ivar total_psenergy: Pseudopotential energy of the configuration
        used for the pseudopotential configuration (Ry)
    :ivar wfc_cutoff: Suggested plane wave cutoff (Ry)
    :ivar rho_cutoff: Suggested charge density cutoff (Ry)
    :ivar l_max: Maximum angular momentum of a valence orbital.
        !!CHECK!! if the local channel has the maximum angular momentum,
        and it is not empty, is it counted here or not? Would it have
        any effect if it is wrong?
    :ivar l_max_rho: Maximum angular momentum of atomic charge density,
        should be 2*l_max. !!CHECK!! same as l_max
    :ivar l_local: If local potential was generated by inversion of a
        norm-conserving wave function, then l_local is equal to the l of
        this channel. If the local potential was generated by some other
        means, e.g. smoothing the all-electron potential, then l_local
        &lt; 0. The atomic code in QE uses l_local=-1, if the smoothing
        was done with two Bessel functions (RRKJ optimized) and
        l_local=-2, of it was done with the Troullier-Martins recipe.
        Note that the local potential always has spherical symmetry.
        This attribute is actually unused in the plane-wave code (stored
        only for reconstruction purposes).
    :ivar mesh_size: Number of points in the radial grid, on which
        potential, wave functions and other quantities are stored. Note:
        the number of mesh points for the potential and the wave
        functions may in principle be different. This is not allowed in
        the UPF 2.0.1 format.
    :ivar number_of_wfc: Number of wave functions stored in the file.
        These wave functions are used by QE programs only to bootstrap
        self-consistency. Note: In the PAW case, these are *not* the
        wave functions used for the one-center terms. They are used ONLY
        to generate the initial charge density to bootstrap the self-
        consistent cycle.
    :ivar number_of_proj: Number of Kleinman-Bylander projectors in the
        pseudopotential. In the PAW formalism, this is also the number
        of wavefunctions used in one-center terms. Many other
        quantities, e.g. the number of augmentation channels, depend on
        the value of number_of_proj. If the pseudopotential has no
        projectors, number_of_proj must be set to zero.
    :ivar has_wfc: Deprecated??
    :ivar paw_as_gipaw: Deprecated??
    """

    class Meta:
        name = "PP_HEADER"

    element: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 2,
            "white_space": "collapse",
            "pattern": r"[A-Za-z]+",
        },
    )
    generated: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "max_length": 80,
        },
    )
    author: str = field(
        default="anonymous",
        metadata={
            "type": "Attribute",
            "max_length": 80,
        },
    )
    date: Optional[object] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    comment: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "max_length": 200,
        },
    )
    pseudo_type: Optional[UpfPseudotype] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    relativistic: Optional[UpfRelativisticType] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    is_ultrasoft: Optional[UpfLogical] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    is_paw: Optional[UpfLogical] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    is_coulomb: UpfLogical = field(
        default=UpfLogical.FALSE,
        metadata={
            "type": "Attribute",
        },
    )
    has_so: UpfLogical = field(
        default=UpfLogical.FALSE,
        metadata={
            "type": "Attribute",
        },
    )
    has_gipaw: UpfLogical = field(
        default=UpfLogical.FALSE,
        metadata={
            "type": "Attribute",
        },
    )
    core_correction: Optional[UpfLogical] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    functional: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 20,
        },
    )
    z_valence: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    total_psenergy: float = field(
        default=0.0,
        metadata={
            "type": "Attribute",
        },
    )
    wfc_cutoff: float = field(
        default=0.0,
        metadata={
            "type": "Attribute",
        },
    )
    rho_cutoff: float = field(
        default=0.0,
        metadata={
            "type": "Attribute",
        },
    )
    l_max: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    l_max_rho: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    l_local: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    mesh_size: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    number_of_wfc: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    number_of_proj: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    has_wfc: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    paw_as_gipaw: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class UpfDataSection:
    class Meta:
        name = "upf-data-section"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    type_value: Optional[UpfDataType] = field(
        default=None,
        metadata={
            "name": "type",
            "type": "Attribute",
            "required": True,
        },
    )
    size: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    columns: int = field(
        default=4,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class PpAeNlcc(UpfDataSection):
    """The all-electron core charge (no factors r^2 or 4\\pi as in PP_NLCC).

    Note: This section must be present even when the
    attribute 'core_correction' of section PP_HEADER is false
    in order to correctly reproduce the all-electron energy.
    Dimension: mesh_size
    """

    class Meta:
        name = "PP_AE_NLCC"


@dataclass
class PpAeVloc(UpfDataSection):
    """The all-electron valence potential.

    Dimension: mesh_size
    """

    class Meta:
        name = "PP_AE_VLOC"


@dataclass
class PpGipawOrbitalAe(UpfDataSection):
    """Contains all-electron valence orbital.

    Note: The orbitals are stored multiplied by a factor of r.
    I.e. their square module already contain the factor r^2 of
    the spherical volume element.
    """

    class Meta:
        name = "PP_GIPAW_ORBITAL_AE"


@dataclass
class PpGipawOrbitalPs(UpfDataSection):
    """Contains pseudo valence orbital.

    Note: The orbitals are stored multiplied by a factor of r.
    I.e. their square module already contain the factor r^2 of
    the spherical volume element.
    """

    class Meta:
        name = "PP_GIPAW_ORBITAL_PS"


@dataclass
class PpGipawVlocalAe(UpfDataSection):
    """Contains all-electron local potential corresponding to GIPAW orbitals.

    Note: The potential is stored multiplied by a factor of r
    (different from PP_VLOC).
    """

    class Meta:
        name = "PP_GIPAW_VLOCAL_AE"


@dataclass
class PpGipawVlocalPs(UpfDataSection):
    """Contains pseudo local potential corresponding to GIPAW orbitals.

    Note: The potential is stored multiplied by a factor of r
    (different from PP_VLOC).
    """

    class Meta:
        name = "PP_GIPAW_VLOCAL_PS"


@dataclass
class PpLocal(UpfDataSection):
    """Data section containing the local potential sampled in the radial grid (Ry).

    The potential does not contain the effect of the net valence charge
    (-e2*z_valence/r_i), which will be added directly in the plane-wave
    code. Igonred if is_coulomb (PP_HEADER).
    """

    class Meta:
        name = "PP_LOCAL"


@dataclass
class PpMultipoles(UpfDataSection):
    """The electrostatic multipoles of the corresponding augmentation channel.

    If the absolute value of a multipole is less than augmentation_epsilon,
    the corresponding function will be considered zero.
    Note: This section is compulsory for PAW and ignored otherwise.
    """

    class Meta:
        name = "PP_MULTIPOLES"


@dataclass
class PpNlcc(UpfDataSection):
    """Data section containing the pseudized core charge used for non-linear core
    correction sampled on the radial grid stored in PP_R.

    It is the true charge density, i.e. it will be correctly integrated
    as \\sum_i 4 \\pi r_i^2 nlcc_i Ignored if core_correction is false.
    """

    class Meta:
        name = "PP_NLCC"


@dataclass
class PpOccupations(UpfDataSection):
    """Occupations used in the atomic reference configuration.

    Note: For higher energy projectors, this occupation will
    typically be zero. They are used as an initial condition for the
    self-consistency of the terms
    \\rho_{ij} = \\sum_b f_b \\langle \\beta_i | \\psi_b \\rangle
    \\langle \\psi_b | \\beta_j \\rangle
    Dimensions: number_of_proj
    """

    class Meta:
        name = "PP_OCCUPATIONS"


@dataclass
class PpQ(UpfDataSection):
    """The norm of the augmentation functions.

    Note: The fact that Q is zero for a certain augmentation function
    does not guarantee that the function will be identically zero.
    This was erroneously assumed in UPF 2.0.0, causing small errors
    in specific cases.
    """

    class Meta:
        name = "PP_Q"


@dataclass
class PpQfcoeff(UpfDataSection):
    """The coefficient used to perform a Taylor expansion of the augmentation
    functions at small radii.

    Note: Compulsory if nqf &gt; 0, ignored otherwise.
    """

    class Meta:
        name = "PP_QFCOEFF"


@dataclass
class PpR(UpfDataSection):
    """Data section containing the radial grid, on which quantities such as local
    potential, wave functions, projectors and augmentation charges are sampled.

    The ith value of these quantities corresponds to the ith element of
    the radial grid.
    """

    class Meta:
        name = "PP_R"


@dataclass
class PpRab(UpfDataSection):
    """Data section containing the radial volume element.
    These attributes have been used to generate the logarithmic grid on
    which the pseudopotential is constructed.
    The expression insode the atomic code of QE is:
    r(i) = exp ( xmin + (i-1) dx ) / zmesh i=1,mesh
    r_ab(i) = r(i) * dx
    For PAW, this is the only acceptable grid (required in V_H).
    Otherwise, any kind of grid is accepted, if it can be used to compute
    a Simpson numerical integral according to the formula
    \\sum_i c_i f(i)*rab(i) = \\int_0^\\infty f_i dr
    where c_i are alternativly 2/3 and 4/3, except c_1=c_mesh=1/3.
    f_i is a generic function, such as the atomic wave function, sampled on
    the grid r(i): f_i = f(r_i). An equivalent definition of rab is
    rab(i) = dr(x) / dx | x= i"""

    class Meta:
        name = "PP_RAB"


@dataclass
class PpRhoatom(UpfDataSection):
    """The valence charge density in the reference atomic configuration.

    Can be used to genreate the initial charge density in the self-
    consistent calculation. This quantity is stored multiplied by a
    factor of r^2.
    """

    class Meta:
        name = "PP_RHOATOM"


@dataclass
class PpRinner(UpfDataSection):
    """
    The radius before which the augmentation functions are expanded in a Taylor
    series.
    """

    class Meta:
        name = "PP_RINNER"


@dataclass
class UpfGipawCoreOrbitalN(UpfDataSection):
    """Contains all-electron orbital for particular projector.

    The index n ranges from 1 to number_of_proj.
    Note: The orbitals are stored multiplied by a factor of r.
    I.e. their square module already contain the factor r^2 of
    the spherical volume element.
    Dimension: mesh_size

    :ivar index: UNDOCUMENTED The index n in PP_GIPAW_CORE_ORBITAL.n
    :ivar l: Angular momentum quantum number of the wave function.
    :ivar n: Principal quantum number of the wave function.
    :ivar label: A conventional label for the wave function, such as
        '2S', '3P', etc.
    """

    class Meta:
        name = "upf-GIPAW_CORE_ORBITAL.n"

    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    l: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    n: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 2,
        },
    )


@dataclass
class UpfPpAewfcN(UpfDataSection):
    """Contains one all-electron orbital for each projector.

    The index n ranges from 1 to number_of_proj.
    Note: The orbitals are stored multiplied by a factor of r.
    I.e. their square module already contain the factor r^2 of
    the spherical volume element.
    Dimension: mesh_size

    :ivar index: UNDOCUMENTED Maybe: The index n in PP_AEWFC.n
    :ivar l: UNDOCUMENTED Maybe: Angular momentum of the wave function.
    :ivar label: UNDOCUMENTED Maybe: A conventional label, such as '2S',
        '3P', etc.
    """

    class Meta:
        name = "upf-PP_AEWFC.n"

    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    l: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 2,
        },
    )


@dataclass
class UpfPpBetaN(UpfDataSection):
    """Contains a Kleinman-Bylander projector sampled on the radial grid.

    If number_of_proj &gt; 0, there must be a PP_BETA.n section for each
    n between 1 and number_of_proj.

    :ivar index: For PP_BETA.n, this is just n. TODO do away with the
        PP_BETA.n naming scheme.
    :ivar angular_momentum: The angular momentum of the projector.
    :ivar cutoff_radius_index: The projector is assumed to be zero
        beyond this point. If it is not specified, it is assumed to be
        equal to the mesh size. NOTE: Not specifying cutoff_radius can
        introduce a considerable numerical noise in some integrals,
        especially in the PAW case.
    :ivar cutoff_radius: The value of the radial mesh point
        corresponding to cutoff_radius_index. This value is currently
        unused in the plane-wave code.
    :ivar norm_conserving_radius: Value of norm conserving wave function
        used to generate the ultrasoft pseudopotential. Ununsed in the
        code, stored only for reconstruction purposes, meaningless for
        PAW.
    :ivar ultrasoft_cutoff_radius: UNDOCUMENTED
    :ivar label: UNDOCUMENTED
    """

    class Meta:
        name = "upf-PP_BETA.n"

    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    angular_momentum: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    cutoff_radius_index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    cutoff_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    norm_conserving_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    ultrasoft_cutoff_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class UpfPpChiN(UpfDataSection):
    """An atomic wave function sampled on the radial grid.

    They are use in QE as initial conditions for the self-consistent
    calculation.
    Note: There is no link between these wave functions and the beta
    projectors in PP_NONLOCAL. number_of_wfc can be different from
    number_of_proj.
    This quantity is stored multiplied by a factor r.

    :ivar l: Angular momentum of the wave function.
    :ivar occupation: Occupation of the wave function in the reference
        configuration.
    :ivar index: The index n in PP_CHI.n
    :ivar label: A conventional label, such as '2S', '3P', etc.
    :ivar n: Pseudo-principal quantum number. Usually set to l-1. Only
        stored for reconstruction purposes.
    :ivar pseudo_energy: Single-particle energy of the wave function in
        atomic configuration.
    :ivar cutoff_radius: Inner norm-conserving radius used by atomic
        code in QE. Only stored for reconstruction purposes.
    :ivar ultrasoft_cutoff_radius: Outer ultrasoft radius used by atomic
        code in QE. Only stored for reconstruction purposes. A
        conventional label, such as '2S', '3P', etc.
    """

    class Meta:
        name = "upf-PP_CHI.n"

    l: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    occupation: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "max_length": 2,
        },
    )
    n: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    pseudo_energy: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    cutoff_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    ultrasoft_cutoff_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class UpfPpPswfcN(UpfDataSection):
    """Contains one pseudo orbital for each projector.

    The index n ranges from 1 to number_of_proj.
    Note: The orbitals are stored multiplied by a factor of r.
    I.e. their square module already contain the factor r^2 of
    the spherical volume element.
    Dimension: mesh_size

    :ivar index: UNDOCUMENTED Maybe: The index n in PP_PSWFC.n
    :ivar l: UNDOCUMENTED Maybe: Angular momentum of the wave function.
    :ivar label: UNDOCUMENTED Maybe: A conventional label, such as '2S',
        '3P', etc.
    """

    class Meta:
        name = "upf-PP_PSWFC.n"

    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    l: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 2,
        },
    )


@dataclass
class UpfPpQijlNNN(UpfDataSection):
    """If q_with_l is true, there needs to be one PP_Q.i.j.l section for each i and
    j from 1 to number_of_proj and l from 0 to l_max_rho. If q_with_l is false,
    there needs to be one PP_Q.i.j section for each i and j from 1 to
    number_of_proj. An augmentation function can be omitted (or replaced with an
    empty section of the same name), if at least one of the following conditions.

    is met:
    - It is identically zero. In this case, an empty section must be
    present (see is_null).
    - j &lt; i (Q_ij = Q_ji due to symmetry).
    - The pseudo is of PAW type and the corresponding multipole
    (PP_MULTIPOLES) is zero or less than augmentation_epsilon
    - q_with_l is true and l is *not* taken from the list
    abs(l_i-l_j), abs(l_i-l_j)+2 ... l_i+l_j-2, l_i+l_j .
    Unnecessary sections with augmentation charges are ignored.

    :ivar angular_momentum: To be documented.
    :ivar first_index: The index i of the function.
    :ivar second_index: The index j of the function.
    :ivar composite_index: A composite index k = j*(J-1)/2 + i, used
        internally to save memory.
    :ivar is_null: If an augmentation function is identically zero, the
        data section can be replaced by an empty section that is_null.
    """

    class Meta:
        name = "upf-PP_QIJL.n.n.n"

    angular_momentum: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    first_index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    second_index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    composite_index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    is_null: Optional[UpfLogical] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class UpfPpRelbetaN(UpfDataSection):
    """Contains data necessary to perform a spin-orbit self-consistent calculation.

    For each projector in section PP_NONLOCAL, there must be one empty
    section of this kind. The index n runs from 1 to number_of_proj.

    :ivar index: The index n in PP_RELBETA.n
    :ivar jjj: Total angular momentum of the wave function.
    :ivar lll: See attribute 'angular_momentum' or corresponding
        PP_BETA.n subsection of PP_NONLOCAL (whose value is used as
        default).
    """

    class Meta:
        name = "upf-PP_RELBETA.n"

    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    jjj: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    lll: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class UpfPpRelwfcN(UpfDataSection):
    """Contains data necessary to perform a spin-orbit self-consistent calculation.

    For each wave function stored in the PP_PSWFC section, there must be
    one empty section of this kind. The index n runs from 1 to
    number_of_wfc.

    :ivar jchi: Total angular momentum of the wave function, i.e. l+1/2,
        l-1/2 when l&gt;0.
    :ivar index: The index n in PP_RELWFC.n
    :ivar els: A conventional label for the wave function, such as '2S',
        '3P', etc.
    :ivar nn: The actual principal quantum number. Note: This can differ
        from the pseudo-principal quantum number stored in the 'nchi'
        attribute of PP_CHI.n
    :ivar lchi: See attribute 'lchi' of PP_CHI.n (which is used as
        default).
    :ivar oc: See attribute 'occupations' of PP_CHI.n (which is used as
        default).
    """

    class Meta:
        name = "upf-PP_RELWFC.n"

    jchi: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    els: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "max_length": 2,
        },
    )
    nn: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    lchi: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    oc: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class UpfPpVnlN(UpfDataSection):
    """
    Contains the pseudopotential for l and j specified in the attribute list.
    """

    class Meta:
        name = "upf-PP_VNL.n"


@dataclass
class PpAugmentation:
    """
    Compulsory for pseudopotentials with augmentation charge, i.e. when the
    pseudopotential is_ultrasoft (presently ultrasoft or PAW).

    :ivar pp_q:
    :ivar pp_multipoles:
    :ivar pp_qfcoeff:
    :ivar pp_rinner:
    :ivar pp_qijl_1_1_0:
    :ivar q_with_l: If true, the augmentation charge can depend on the
        value of the angular momentum. I.e. if a certain channel has
        more than one angular momentum component, there shall be a
        different radial form of the augmentation for each component.
        This attribute is false for Vanderbilt's original recipe. It is
        true for PAW.
    :ivar nqf: Specifies the number of coefficients used to analytically
        expand the augmentation charge at small radius, according to
        Vanderbilt's recipe. Note: The analytical expansion of
        augmentation charge is currently not implemented for PAW.
    :ivar nqlc: Specifies the number of angular momentum components that
        can be present in the charge density, when the maximum angular
        momentum for wave functions is l_max (default: nqlc =
        2*l_max+1). If nqf &gt; 0, nqlc is the dimension of several
        arrays. If nqf = 0, nqlc is not used.
    :ivar shape: Describes the kind of pseudization used for the
        augmentation function. Currently unused, stored only for
        reconstructio purpose. Note: If the analytical overlap for PAW
        augmentation charge (as defined by Bloechl) will ever be
        implemented, this field will become necessary.
    :ivar iraug: All augmentation charge must be zero beyond this point.
        Used only for PAW and only if it is greater than cutoff_radius
        for all projectors. If not specified, iraug is set to mesh size.
        This default works, but can generate numerical noise in some
        integrals. In order to avoid large round-off errors in
        cancellation of PAW terms, it is important to set this paramter
        as small as possible, i.e. just outside the augmentation radius.
    :ivar raug: The value of the radial mesh point corresponding to
        iraug.
    :ivar augmentation_epsilon: If augmentation_epsilon &gt; 0,
        augmentation functions, whose norm is less than
        augmentation_epsilon will be considered zero.
    :ivar cutoff_r: Deprecated?
    :ivar cutoff_r_index: Deprecated?
    :ivar l_max_aug: Deprecated?
    """

    class Meta:
        name = "PP_AUGMENTATION"

    pp_q: Optional[PpQ] = field(
        default=None,
        metadata={
            "name": "PP_Q",
            "type": "Element",
            "required": True,
        },
    )
    pp_multipoles: Optional[PpMultipoles] = field(
        default=None,
        metadata={
            "name": "PP_MULTIPOLES",
            "type": "Element",
            "required": True,
        },
    )
    pp_qfcoeff: Optional[PpQfcoeff] = field(
        default=None,
        metadata={
            "name": "PP_QFCOEFF",
            "type": "Element",
            "required": True,
        },
    )
    pp_rinner: Optional[PpRinner] = field(
        default=None,
        metadata={
            "name": "PP_RINNER",
            "type": "Element",
            "required": True,
        },
    )
    pp_qijl_1_1_0: Optional[UpfPpQijlNNN] = field(
        default=None,
        metadata={
            "name": "PP_QIJL.1.1.0",
            "type": "Element",
        },
    )
    q_with_l: Optional[UpfLogical] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    nqf: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    nqlc: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    shape: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "max_length": 20,
        },
    )
    iraug: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    raug: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    augmentation_epsilon: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    cutoff_r: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    cutoff_r_index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    l_max_aug: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class PpGipawCoreOrbitals:
    """
    Contains the all-electron core orbitals.

    :ivar pp_gipaw_core_orbital_n:
    :ivar number_of_core_orbitals: The number of core orbitals included
        in the data set.
    """

    class Meta:
        name = "PP_GIPAW_CORE_ORBITALS"

    pp_gipaw_core_orbital_n: Optional[UpfPpAewfcN] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_CORE_ORBITAL.n",
            "type": "Element",
        },
    )
    number_of_core_orbitals: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class PpGipawOrbitals:
    """
    Contains the valence pseudo and all-electron orbitals.
    """

    class Meta:
        name = "PP_GIPAW_ORBITALS"

    pp_gipaw_orbital_n: Optional[UpfPpAewfcN] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_ORBITAL.n",
            "type": "Element",
        },
    )


@dataclass
class PpGipawVlocal:
    """
    Contains the valence pseudo and all-electron orbitals.
    """

    class Meta:
        name = "PP_GIPAW_VLOCAL"

    pp_gipaw_vlocal_ae: Optional[PpGipawVlocalAe] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_VLOCAL_AE",
            "type": "Element",
            "required": True,
        },
    )
    pp_gipaw_vlocal_ps: Optional[PpGipawVlocalPs] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_VLOCAL_PS",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class PpMesh:
    """
    Defines the mesh.

    :ivar pp_r:
    :ivar pp_rab:
    :ivar dx: r(i) = exp ( xmin + (i-1) dx ) / zmesh i=1,mesh r_ab(i) =
        r(i) * dx
    :ivar xmin: r(i) = exp ( xmin + (i-1) dx ) / zmesh i=1,mesh r_ab(i)
        = r(i) * dx
    :ivar zmesh: r(i) = exp ( xmin + (i-1) dx ) / zmesh i=1,mesh r_ab(i)
        = r(i) * dx
    :ivar mesh: Deprecated. Use mesh_size in PP_HEADER instead.
    :ivar rmax: Deprecated??
    """

    class Meta:
        name = "PP_MESH"

    pp_r: Optional[PpR] = field(
        default=None,
        metadata={
            "name": "PP_R",
            "type": "Element",
            "required": True,
        },
    )
    pp_rab: Optional[PpRab] = field(
        default=None,
        metadata={
            "name": "PP_RAB",
            "type": "Element",
            "required": True,
        },
    )
    dx: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    xmin: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    zmesh: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    mesh: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    rmax: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class PpPaw:
    """Contains additional information required to perform projector-augmented
    self-consistent calculation, i.e. an all-electron wave function for each
    projector, the all-electron local potential as well as the all-electron core
    charge for non-linear core correction.

    The section (as well as PP_MULTIPOLES and PP_NONLOCAL) must be
    present if 'is_paw' in section PP_HEADER is true.  Otherwise it is
    ignored.

    :ivar pp_occupations:
    :ivar pp_ae_nlcc:
    :ivar pp_ae_vloc:
    :ivar pp_aewfc_1:
    :ivar pp_pswfc_1:
    :ivar core_energy: Constant that has to be added to the valence
        energy in order to obtain the all-electron energy. As it is a
        constant, it has no effect on the result of the calculation.
        Only used, if all atoms of the system are described by PAW data
        sets.
    :ivar paw_data_format: UNDOCUMENTED See gipaw_data_format of
        PP_GIPAW section.
    """

    class Meta:
        name = "PP_PAW"

    pp_occupations: Optional[PpOccupations] = field(
        default=None,
        metadata={
            "name": "PP_OCCUPATIONS",
            "type": "Element",
            "required": True,
        },
    )
    pp_ae_nlcc: Optional[PpAeNlcc] = field(
        default=None,
        metadata={
            "name": "PP_AE_NLCC",
            "type": "Element",
            "required": True,
        },
    )
    pp_ae_vloc: Optional[PpAeVloc] = field(
        default=None,
        metadata={
            "name": "PP_AE_VLOC",
            "type": "Element",
            "required": True,
        },
    )
    pp_aewfc_1: Optional[UpfPpAewfcN] = field(
        default=None,
        metadata={
            "name": "PP_AEWFC.1",
            "type": "Element",
        },
    )
    pp_pswfc_1: Optional[UpfPpPswfcN] = field(
        default=None,
        metadata={
            "name": "PP_PSWFC.1",
            "type": "Element",
        },
    )
    core_energy: float = field(
        default=0.0,
        metadata={
            "type": "Attribute",
        },
    )
    paw_data_format: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class PpPswfc:
    """Contains number_of_wfc data sections of the radial sample of an atomic wave
    function.

    These wave functions are used to set up the initial wave functions
    for the self-consistent calculation.
    """

    class Meta:
        name = "PP_PSWFC"

    pp_chi_1: Optional[UpfPpChiN] = field(
        default=None,
        metadata={
            "name": "PP_CHI.1",
            "type": "Element",
        },
    )
    pp_chi_2: Optional[UpfPpChiN] = field(
        default=None,
        metadata={
            "name": "PP_CHI.2",
            "type": "Element",
        },
    )


@dataclass
class PpSemilocal:
    """Contains number_of_proj subsections PP_VNL for PPs in semilocal form.

    Not used by QE.
    """

    class Meta:
        name = "PP_SEMILOCAL"

    pp_vnl_1: Optional[UpfPpVnlN] = field(
        default=None,
        metadata={
            "name": "PP_VNL.1",
            "type": "Element",
        },
    )


@dataclass
class PpSpinOrb:
    """Contains additional information required to perform self consistent
    calculations with spin-orbit coupling.

    The section must be present if 'has_so' in section PP_HEADER is
    true.  Otherwise it is ignored.
    """

    class Meta:
        name = "PP_SPIN_ORB"

    pp_relwfc_1: Optional[UpfPpRelwfcN] = field(
        default=None,
        metadata={
            "name": "PP_RELWFC.1",
            "type": "Element",
        },
    )
    pp_relbeta_1: Optional[UpfPpRelbetaN] = field(
        default=None,
        metadata={
            "name": "PP_RELBETA.1",
            "type": "Element",
        },
    )


@dataclass
class UpfGipawOrbitalN:
    """Contains all-electron orbital for particular projector.

    The index n ranges from 1 to number_of_proj.
    Note: The orbitals are stored multiplied by a factor of r.
    I.e. their square module already contain the factor r^2 of
    the spherical volume element.
    Dimension: mesh_size

    :ivar pp_gipaw_orbital_ae:
    :ivar pp_gipaw_orbital_ps:
    :ivar index: UNDOCUMENTED The index n in PP_GIPAW_CORE_ORBITAL.n
    :ivar l: Angular momentum quantum number of the wave function.
    :ivar n: Principal quantum number of the wave function.
    :ivar label: A conventional label for the wave function, such as
        '2S', '3P', etc.
    :ivar cutoff_radius: Inner norm-conserving cutoff radius. Used as
        core radius by the GIPAW code.
    :ivar ultrasoft_cutoff_radius: Outer ultra-soft cutoff radius.
    """

    class Meta:
        name = "upf-GIPAW_ORBITAL.n"

    pp_gipaw_orbital_ae: Optional[PpGipawOrbitalAe] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_ORBITAL_AE",
            "type": "Element",
            "required": True,
        },
    )
    pp_gipaw_orbital_ps: Optional[PpGipawOrbitalPs] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_ORBITAL_PS",
            "type": "Element",
            "required": True,
        },
    )
    index: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    l: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    n: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 2,
        },
    )
    cutoff_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
    ultrasoft_cutoff_radius: Optional[float] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class PpGipawReconstruction:
    """Contains additional information required by the GIPAW code in order to
    reconstruct the all-electron charge density and to calculate the NMR response.

    This section must be present, if 'has_gipaw' in section PP_HEADER
    is true.
    Note: This section is independent of the PP_PAW section.

    :ivar pp_gipaw_core_orbitals:
    :ivar pp_gipaw_orbitals:
    :ivar pp_gipaw_vlocal:
    :ivar gipaw_data_format: Format version string composed of three
        dot-separated integers. Current version is "0.1.0".
    """

    class Meta:
        name = "PP_GIPAW_RECONSTRUCTION"

    pp_gipaw_core_orbitals: Optional[PpGipawCoreOrbitals] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_CORE_ORBITALS",
            "type": "Element",
            "required": True,
        },
    )
    pp_gipaw_orbitals: Optional[PpGipawOrbitals] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_ORBITALS",
            "type": "Element",
            "required": True,
        },
    )
    pp_gipaw_vlocal: Optional[PpGipawVlocal] = field(
        default=None,
        metadata={
            "name": "PP_GIPAW_VLOCAL",
            "type": "Element",
            "required": True,
        },
    )
    gipaw_data_format: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass
class PpNonlocal:
    """
    Content of this section depends on several settings in PP_HEADER.
    """

    class Meta:
        name = "PP_NONLOCAL"

    pp_beta: list[UpfPpBetaN] = field(
        default_factory=list,
        metadata={
            "name": "PP_BETA",
            "type": "Element",
        },
    )
    pp_dij: Optional[PpDij] = field(
        default=None,
        metadata={
            "name": "PP_DIJ",
            "type": "Element",
            "required": True,
        },
    )
    pp_augmentation: Optional[PpAugmentation] = field(
        default=None,
        metadata={
            "name": "PP_AUGMENTATION",
            "type": "Element",
        },
    )


@dataclass
class Upf:
    """
    Root section.
    """

    class Meta:
        name = "UPF"

    pp_info: Optional[PpInfo] = field(
        default=None,
        metadata={
            "name": "PP_INFO",
            "type": "Element",
        },
    )
    pp_header: Optional[PpHeader] = field(
        default=None,
        metadata={
            "name": "PP_HEADER",
            "type": "Element",
            "required": True,
        },
    )
    pp_mesh: Optional[PpMesh] = field(
        default=None,
        metadata={
            "name": "PP_MESH",
            "type": "Element",
            "required": True,
        },
    )
    pp_nlcc: Optional[PpNlcc] = field(
        default=None,
        metadata={
            "name": "PP_NLCC",
            "type": "Element",
        },
    )
    pp_local: Optional[PpLocal] = field(
        default=None,
        metadata={
            "name": "PP_LOCAL",
            "type": "Element",
            "required": True,
        },
    )
    pp_semilocal: Optional[PpSemilocal] = field(
        default=None,
        metadata={
            "name": "PP_SEMILOCAL",
            "type": "Element",
        },
    )
    pp_nonlocal: Optional[PpNonlocal] = field(
        default=None,
        metadata={
            "name": "PP_NONLOCAL",
            "type": "Element",
            "required": True,
        },
    )
    pp_pswfc: Optional[PpPswfc] = field(
        default=None,
        metadata={
            "name": "PP_PSWFC",
            "type": "Element",
            "required": True,
        },
    )
    pp_rhoatom: Optional[PpRhoatom] = field(
        default=None,
        metadata={
            "name": "PP_RHOATOM",
            "type": "Element",
            "required": True,
        },
    )
    pp_paw: Optional[PpPaw] = field(
        default=None,
        metadata={
            "name": "PP_PAW",
            "type": "Element",
        },
    )
    version: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "max_length": 14,
            "pattern": r"[0-9\.]+",
        },
    )
