"""Reproducibility metadata for human-readable LORRAX output files.

Every text-format writer in ``file_io.sigma_output`` and ``gw.eqp_bgw``
prepends ``provenance_header()`` so a stray ``eqp0.dat`` on disk months
from now still tells you which LORRAX version produced it.
"""
from __future__ import annotations

import datetime


def lorrax_version() -> str:
    """Return the installed lorrax package version, or ``"unknown"``."""
    try:
        from importlib.metadata import version
        return version("lorrax")
    except Exception:
        return "unknown"


def provenance_header(*, comment: str = "#") -> str:
    """Return one comment line stamping LORRAX version + UTC timestamp.

    The comment marker defaults to ``#`` (works for ``.dat`` files and the
    BGW eqp{0,1}.dat parsers); pass ``comment="//"`` etc. for other formats.
    """
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%d %H:%M:%S UTC")
    return f"{comment} Generated by LORRAX {lorrax_version()} at {stamp}\n"
