"""BerkeleyGW ``eqp0.dat`` / ``eqp1.dat`` writer for LORRAX gw_jax outputs.

Reproduces the exact text format BerkeleyGW emits at
``Sigma/sigma_main.f90:3174-3193`` so the BSE / band-structure interface
files from a LORRAX gw_jax run are byte-identical (modulo numerics) to
a reference BGW Sigma run.

Physics
-------
We never materialize ``V_xc`` itself — the standard rearrangement

    E_DFT(k,n) = K + I + V_H + V_xc       (mean-field eigenvalue)
    E_GW(k,n,ω) = K + I + V_H + Σ_xc(ω)

means

    Δ(k,n,ω) ≡ E_GW(ω) - E_DFT
            = (K + I + V_H + Σ_xc(ω)) - E_DFT
            = kin_ion[k,n,n] + V_H[k,n,n] + Σ_xc[k,n,n](ω) - E_DFT[k,n]

reads directly off LORRAX outputs without ever forming ``V_xc``.  The
diagonal QP energies BGW writes are the standard Newton iteration on
the on-shell Σ:

    eqp0[k,n] = E_DFT[k,n] + Δ(k,n, E_DFT[k,n])               (zeroth order)
    eqp1[k,n] = E_DFT[k,n] + Z[k,n] · Δ(k,n, E_DFT[k,n])      (linearized)
    Z[k,n]   = 1 / (1 - dRe[Σ_c]/dω | ω = E_DFT[k,n])

Σ_x and V_H are ω-independent, so only Σ_c contributes to Z.

Inputs (per LORRAX gw_jax run directory)
----------------------------------------
- ``WFN.h5``                 — IBZ wedge k-points + DFT energies in Ry
- ``kin_ion.h5``             — K+I matrix elements in Ry (nk_full, nb, nb).
                               When stamped ``has_hartree=True`` it ALSO
                               contains the exact FFT-grid ⟨V_H⟩, and this
                               CLI then suppresses ``sigma_mnk.h5``'s ISDF
                               Hartree column rather than adding it twice
                               (same contract as ``gw.sigma_dispatch``).
- ``sigma_mnk.h5``           — Σ_x, Σ_c(ω), V_H matrix elements in eV; ω in eV
                               relative to the DFT mid-gap Fermi level
- ``qp_wfn_rotations.h5``    — band_range + kirr_to_kfull mapping

Output format (BGW ``Sigma/sigma_main.f90:3175-3193``)
-----------------------------------------------------
A single provenance comment line is prepended:

    # Generated by LORRAX <version> at <UTC ISO timestamp>

then per IBZ k-point one block:

    header  ``(3f13.9, i8)``       kx_frac ky_frac kz_frac (nspin·nb)
    body    ``(2i8, 2f15.9)``      ispin iband_abs E_DFT_eV E_QP_eV

Everything past the comment line is byte-identical to BGW's own
``eqp.dat``.  The LORRAX reader (:func:`bse.bse_io.read_bgw_eqp`)
transparently skips leading ``#`` lines; for downstream BGW binaries
(BSE/Inteqp) that don't, strip the comment with ``tail -n +2``.

Design — one assembly, one formatter, two ways in
-------------------------------------------------
There are two legitimate ways to want eqp{0,1}: during a live gw_jax run
(the arrays are already in memory) and afterwards from a run directory
(the "rebuild QP energies from artifacts without re-running Σ" workflow,
which proved essential this campaign).  They differ ONLY in how the
arrays are obtained::

        load artifacts              in-memory arrays
              |                            |
    make_eqp_bgw                     gw_output.write_results
              \\                          /
               +---- assemble_eqp() ----+     V_H seam, mean-field gate,
                        |                     Z-factor, Newton update
               EqpAssembly.write()            the BGW formatter

Everything physical happens in :func:`assemble_eqp` — in particular the
V_H seam (:func:`resolve_hartree_diag_ev`), which used to be written out
once here and once in ``gw_output`` and drifted (production job 7874840:
double-counted Hartree, QP gap −453 eV, rc=0).  :func:`make_eqp_bgw` has
no independent semantics left; it cannot produce a different answer from
the driver, only the same answer from different inputs.

CLI
---
    python -m gw.eqp_bgw <run_dir>
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import Optional

import h5py
import numpy as np

from common.units import RYD_TO_EV
from common.provenance import provenance_header


# ---------------------------------------------------------------------------
# Pure formatter (matches BGW sigma_main.f90 byte-for-byte)
# ---------------------------------------------------------------------------

def write_bgw_eqp(
	path: str,
	kpoints_irr_frac: np.ndarray,
	e_dft_ev: np.ndarray,
	e_qp_ev: np.ndarray,
	*,
	band_offset: int,
	nspin: int = 1,
) -> str:
	"""Write a BerkeleyGW ``eqp{0,1}.dat`` file.

	Parameters
	----------
	path
	    Output file path.
	kpoints_irr_frac : (nk, 3)
	    IBZ-wedge k-points in fractional crystal coordinates.
	e_dft_ev, e_qp_ev : (nk, nb)
	    DFT and quasiparticle eigenvalues in eV, indexed over the
	    sigma-window bands.
	band_offset
	    0-based absolute band index of the first sigma-window band; the
	    BGW file uses 1-based labels ``band_offset + 1 .. band_offset + nb``.
	nspin
	    Number of spin channels (LORRAX runs at nspin=1).
	"""
	kpts = np.asarray(kpoints_irr_frac, dtype=np.float64)
	e_dft = np.asarray(e_dft_ev, dtype=np.float64)
	e_qp = np.asarray(e_qp_ev, dtype=np.float64)
	nk, nb = e_dft.shape
	if kpts.shape != (nk, 3):
		raise ValueError(f"kpoints shape {kpts.shape} does not match e_dft {(nk, 3)}")
	if e_qp.shape != (nk, nb):
		raise ValueError(f"e_qp shape {e_qp.shape} does not match e_dft {(nk, nb)}")

	# ── Writer gate (pre-write) ──────────────────────────────────────
	# The NaN-producing distributed back-solve of 2026-07 reached disk
	# with rc=0 and was caught only because somebody afterwards counted
	# the floats in eqp0.dat: ``%15.9f`` renders a NaN as the token
	# ``nan``, so the *count of parseable floats* drops while the line
	# count does not.  That check is made structural here — the writer
	# refuses to pretend a NaN-bearing array is a result, and re-reads
	# what it wrote to confirm the file it produced parses to exactly the
	# expected number of finite floats.
	from common import sanity
	sanity.check_finite(f"{os.path.basename(path)} E_DFT column", e_dft)
	sanity.check_finite(f"{os.path.basename(path)} E_QP column", e_qp)

	abs_path = os.path.abspath(path)
	if os.path.dirname(abs_path):
		os.makedirs(os.path.dirname(abs_path), exist_ok=True)

	with open(abs_path, "w") as fh:
		fh.write(provenance_header())
		for ik in range(nk):
			kx, ky, kz = (float(kpts[ik, j]) for j in range(3))
			# Fortran (3f13.9, i8)
			fh.write(f"{kx:13.9f}{ky:13.9f}{kz:13.9f}{nspin * nb:8d}\n")
			for ispin in range(1, nspin + 1):
				for ib in range(nb):
					iband = band_offset + ib + 1  # 1-based BGW absolute band
					# Fortran (2i8, 2f15.9) — BGW format consumes only 4 args
					# even though the spec advertises 3f15.9; sigma_main.f90 passes
					# (ispin, iband, E_DFT, E_QP).
					fh.write(
						f"{ispin:8d}{iband:8d}"
						f"{float(e_dft[ik, ib]):15.9f}{float(e_qp[ik, ib]):15.9f}\n"
					)
	verify_eqp_file(abs_path, nk=nk, nb=nb, nspin=nspin)
	return abs_path


def verify_eqp_file(
	path: str, *, nk: int, nb: int, nspin: int = 1,
	print_fn=print,
) -> bool:
	"""Re-read a written ``eqp*.dat`` and assert its structural float count.

	The invariant: after the ``#`` provenance line the file holds ``nk``
	k-point headers (3 floats + 1 int) and ``nk·nspin·nb`` body rows
	(2 ints + 2 floats).  So a healthy file parses to exactly

	    n_float = nk·3 + nk·nspin·nb·2

	*finite* floats.  ``float("nan")`` parses fine, so the count alone is
	not enough — non-finite tokens are counted separately and reported.
	This is the check that caught the NaN-producing back-solve after the
	fact; running it inside the writer turns "somebody noticed later" into
	"the run said so at the time".

	Returns True when the file is structurally sound.  Cost is one pass
	over a few-thousand-line text file, i.e. nothing.
	"""
	from common import sanity

	if not sanity.sanity_enabled():
		return True
	expect_rows = int(nk) * int(nspin) * int(nb)
	expect_floats = int(nk) * 3 + expect_rows * 2
	n_float = 0
	n_nonfinite = 0
	n_header = 0
	n_body = 0
	with open(path, "r") as fh:
		for line in fh:
			if line.startswith("#") or not line.strip():
				continue
			tok = line.split()
			# Header rows are (3f13.9, i8) — the first token is a float and
			# carries a '.'.  Body rows are (2i8, 2f15.9) — the first two
			# tokens are bare integers.  Discriminating on content rather
			# than column width keeps this correct if either format ever
			# widens a field.
			if len(tok) == 4 and "." in tok[0]:
				n_header += 1
				vals = tok[:3]
			elif len(tok) == 4:
				n_body += 1
				vals = tok[2:]
			else:
				n_nonfinite += len(tok)   # malformed → count as suspect
				continue
			for v in vals:
				try:
					x = float(v)
				except ValueError:
					n_nonfinite += 1
					continue
				if np.isfinite(x):
					n_float += 1
				else:
					n_nonfinite += 1
	base = os.path.basename(path)
	ok = sanity.check_count(
		f"{base} finite-float count", n_float, expect_floats,
		print_fn=print_fn,
		detail=(f"{n_header}/{nk} k-headers, {n_body}/{expect_rows} band rows, "
		        f"{n_nonfinite} non-finite/unparseable tokens.  A NaN or Inf "
		        f"in the QP column renders as a token %15.9f cannot round-trip "
		        f"— the file looks complete but its numbers are not."))
	ok = sanity.check_count(f"{base} band rows", n_body, expect_rows,
	                        print_fn=print_fn) and ok
	return ok


# ---------------------------------------------------------------------------
# Numerics: eqp0 / eqp1 from per-state Σ on a global ω-grid
# ---------------------------------------------------------------------------

def compute_z_factor_from_omega_grid(
	*,
	sigma_c_omega_diag_ev: np.ndarray,  # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray,           # (n_omega,)  — ω axis relative to E_F
	e_dft_rel_ev: np.ndarray,           # (nk, nb)    — E_DFT - E_F
	dE_ev: float = 0.5,
) -> tuple[np.ndarray, np.ndarray]:
	"""Interpolate Σ_c at E_DFT and central-difference Z = 1 / (1 − dRe[Σ_c]/dω).

	Returns ``(sigma_c_at_dft_diag_ev, z_factor)``, both shape ``(nk, nb)``.
	``sigma_c_at_dft_diag_ev`` is complex; ``z_factor`` is real.

	``dE_ev`` plays the role of BGW's ``finite_difference_spacing``; 0.5 eV
	matches the BGW default.  For the ω-grid spacing of 0.25 eV used by
	gw_jax this falls cleanly on grid points.
	"""
	nk, nb = e_dft_rel_ev.shape
	if sigma_c_omega_diag_ev.shape != (omega_rel_ev.size, nk, nb):
		raise ValueError(
			f"sigma_c_omega shape {sigma_c_omega_diag_ev.shape} mismatched against "
			f"({omega_rel_ev.size}, {nk}, {nb})"
		)

	from .qsgw_utils import interp_along_omega
	sigma_c_at_dft = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev)
	sigma_c_plus = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev + dE_ev)
	sigma_c_minus = interp_along_omega(
		sigma_c_omega_diag_ev, omega_rel_ev, e_dft_rel_ev - dE_ev)

	# Central-difference dRe[Σ_c]/dω at E_DFT
	dsigma_dE = (np.real(sigma_c_plus) - np.real(sigma_c_minus)) / (2.0 * dE_ev)
	z_factor = 1.0 / (1.0 - dsigma_dE)
	return sigma_c_at_dft, z_factor


def _implied_vxc_window_ev() -> tuple[float, float]:
	"""The physical window for ``V_xc = E_DFT − (kin_ion + V_H)``, in eV.

	Single-sources the bounds from ``gw.gw_output`` when that module
	exposes them, so the writer-side gate and the driver-side
	``_warn_on_unphysical_h0`` can never drift apart.  The literals below
	are the same numbers, kept as a fallback so this module stays
	importable on its own (the post-hoc ``python -m gw.eqp_bgw`` CLI does
	not otherwise need the driver).
	"""
	try:
		from . import gw_output as _gwo
		return (float(getattr(_gwo, "_VXC_IMPLIED_MIN_EV", -50.0)),
		        float(getattr(_gwo, "_VXC_IMPLIED_MAX_EV", 2.0)))
	except ImportError:
		return (-50.0, 2.0)


def _warn_on_unphysical_implied_vxc(
	*, e_dft_ev, kin_ion_diag_ev, hartree_diag_ev,
) -> None:
	"""Gate the mean-field side of eqp{0,1} on the DFT eigenvalue identity.

	``E_DFT = ⟨T+V_ion+V_NL⟩ + ⟨V_H⟩ + ⟨V_xc⟩`` is exact, so a correct run
	must reproduce a physical ``V_xc = E_DFT − (kin_ion + V_H)``
	band-by-band.  That is the invariant this checks.

	Why not check the QP shift itself.  The first version of this gate
	bracketed ``Δ = eqp0 − E_DFT`` at ±50 eV, reasoning that GW moves
	states by a few eV.  That is **wrong for deep states**: Δ = Σ_xc −
	V_xc, and semicore bands carry bare-exchange Σ_x of order −100 eV
	against an equally large V_xc, so a perfectly healthy run legitimately
	shows |Δ| ≫ 50 eV.  It fired on 72 of 120 states of the cohsex_debug
	fixture — a run that simultaneously reproduced its reference eqp to
	1e-6 eV.  The implied-V_xc form has no such sensitivity: the large,
	legitimate Σ_xc cancels out of it entirely, because Σ never enters.

	This is deliberately the same invariant, and the same window, as
	``gw_output._warn_on_unphysical_h0``.

	**Status:** since AD, :func:`assemble_eqp` runs the source-aware
	``_warn_on_unphysical_h0`` for BOTH entry points, so this function is
	no longer on the live path.  It is retained as (a) the fallback the
	assembly uses when ``gw.gw_output`` is not importable (no jax on the
	host — the post-hoc CLI's own environment) and (b) the ``common.sanity``
	spelling of the same bracket, which the pure-python gate suite calls
	directly.  Warn-only; prints nothing on a healthy run.
	"""
	from common import sanity

	if not sanity.sanity_enabled():
		return
	implied_vxc = (np.asarray(e_dft_ev, dtype=np.float64)
	               - (np.asarray(kin_ion_diag_ev, dtype=np.float64)
	                  + np.real(np.asarray(hartree_diag_ev))))
	lo, hi = _implied_vxc_window_ev()
	sanity.check_in_range(
		"implied Vxc = E_DFT − (kin_ion + V_H)", implied_vxc, lo, hi,
		unit="eV")


def compute_eqp_diag(
	*,
	kin_ion_diag_ev: np.ndarray,        # (nk, nb)
	hartree_diag_ev: np.ndarray,        # (nk, nb)
	sigma_x_diag_ev: np.ndarray,        # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray, # (nk, nb)  — on-shell Σ_c
	e_dft_ev: np.ndarray,               # (nk, nb)
	z_factor: np.ndarray | None = None, # (nk, nb)  — None ⇒ Z=1 (static modes)
) -> tuple[np.ndarray, np.ndarray]:
	"""Return zeroth-order and Z-linearized BGW QP energies.

	Computes::

	    Δ(k,n)  = (kin_ion + V_H + Σ_x + Σ_c(E_DFT) − E_DFT).real
	    eqp0    = E_DFT + Δ                          (zeroth-order Newton)
	    eqp1    = E_DFT + Z · Δ                      (linearized; Z=1 if None)

	For static modes (COHSEX) the on-shell Σ_c is just the static value and
	there is no ω-grid to differentiate, so callers pass ``z_factor=None``
	and ``eqp1 == eqp0`` trivially — matching BGW's behavior in static runs.

	For dynamic modes (GN-PPM, HL-PPM) the caller obtains both
	``sigma_c_at_dft_diag_ev`` and ``z_factor`` from
	:func:`compute_z_factor_from_omega_grid`.
	"""
	sigma_xc_at_dft = sigma_x_diag_ev + sigma_c_at_dft_diag_ev
	delta_at_dft = (
		kin_ion_diag_ev + hartree_diag_ev + sigma_xc_at_dft - e_dft_ev
	).real

	# NOTE: the mean-field (implied-V_xc) gate deliberately does NOT live
	# here.  ``compute_eqp_diag`` is the pure math kernel, shared by every
	# path including callers that legitimately want no output at all
	# (``gw_output.write_freq_debug``), and a gate here reported one
	# broken H₀ twice in two wordings.  It lives one level up, in
	# :func:`assemble_eqp`, which BOTH entry points go through — so it
	# still fires exactly once on the live driver and on the post-hoc
	# CLI.  Pinned by
	# ``tests/test_sanity_gates.py::test_compute_eqp_diag_does_not_duplicate_the_mean_field_gate``.
	eqp0 = e_dft_ev + delta_at_dft
	if z_factor is None:
		eqp1 = eqp0  # Z=1 trivially
	else:
		eqp1 = e_dft_ev + z_factor * delta_at_dft
	return eqp0, eqp1


# ---------------------------------------------------------------------------
# THE V_H seam — which Hartree term enters H₀, decided in exactly one place
# ---------------------------------------------------------------------------

def resolve_hartree_diag_ev(
	*,
	hartree_diag_ev: np.ndarray,
	hartree_source: str | None = None,
	kin_ion_has_hartree: bool = False,
	exact_hartree_diag_ev: np.ndarray | None = None,
	print_fn=print,
) -> tuple[np.ndarray, str]:
	"""Decide the ⟨mk|V_H|mk⟩ term of H₀.  **The only copy of this rule.**

	H₀ = kin_ion + V_H is a ~500 eV catastrophic cancellation, so counting
	the Hartree term twice — or zero times — is the single most damaging
	mistake either eqp entry point can make (production job 7874840:
	QP gap −453 eV at rc=0).  The three-way rule, from
	``file_io.kin_ion``'s source ladder:

	``folded``   (legacy ``has_hartree=True`` with no ``v_hartree``
	             dataset) — V_H is already inside the ``kin_ion`` values.
	             **Suppress**: the Hartree term is zero here.
	``stored``   — ``kin_ion`` is pristine and the file carries the exact
	             FFT-grid V_H in its own array.  **Substitute** it for
	             whatever Σ-side (ISDF quadrature) column the caller
	             brought, when the caller supplies it.
	other        (``isdf`` / ``gspace`` / ``none`` / unknown) —
	             ``hartree_diag_ev`` *is* the run's V_H.  **Use as given.**

	``exact_hartree_diag_ev`` is the substitution operand and is optional
	on purpose.  On the live driver path ``gw.sigma_dispatch`` has already
	substituted the exact matrix into ``sig_h`` at the one point V_H
	enters ``SigmaResult``, so the caller passes ``None`` and this
	function is a no-op for ``stored``.  On the post-hoc CLI path nothing
	upstream did that, so ``make_eqp_bgw`` reads ``kin_ion.h5``'s
	``v_hartree`` and passes it here.  Either way the decision is made
	once, by this function.

	Reading the file attribute is the only supported discriminator —
	never infer the state from magnitudes (``file_io.kin_ion`` docstring).

	Returns ``(hartree_diag_ev_used, rule)`` where ``rule`` is one of
	``'suppressed'`` / ``'substituted'`` / ``'as-given'``.
	"""
	h = np.real(np.asarray(hartree_diag_ev, dtype=np.float64))
	if bool(kin_ion_has_hartree) or hartree_source == "folded":
		print_fn(
			"  V_H seam: kin_ion carries the exact FFT-grid V_H in its own "
			"values (legacy folded file) — suppressing the Sigma-side "
			f"Hartree column (mean |V_H| = {float(np.mean(np.abs(h))):.3f} eV) "
			"to avoid double counting.")
		return np.zeros_like(h), "suppressed"
	if hartree_source == "stored" and exact_hartree_diag_ev is not None:
		vh = np.real(np.asarray(exact_hartree_diag_ev, dtype=np.float64))
		if vh.shape != h.shape:
			raise ValueError(
				f"exact V_H diagonal shape {vh.shape} does not match the "
				f"Sigma-side Hartree column {h.shape}")
		print_fn(
			"  V_H seam: kin_ion is pristine and carries a stored exact V_H "
			"array — substituting it for the Sigma-side ISDF column "
			f"(mean |V_H| {float(np.mean(np.abs(h))):.3f} → "
			f"{float(np.mean(np.abs(vh))):.3f} eV).")
		return vh, "substituted"
	return h, "as-given"


# ---------------------------------------------------------------------------
# THE assembly — H₀ + Σ → eqp0/eqp1.  Both entry points go through this.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EqpAssembly:
	"""Everything the BGW eqp{0,1} formatter needs, and nothing else.

	Produced by :func:`assemble_eqp` — the *only* place the V_H seam, the
	mean-field gate, the Z-factor and the Newton update are applied — and
	consumed by :meth:`write`, which is the *only* BGW formatter.  The
	live driver (``gw.gw_output.write_results``) and the post-hoc CLI
	(:func:`make_eqp_bgw`) differ solely in how they obtain the input
	arrays; from this object onward the two paths are the same code.
	"""

	kpoints_irr_frac: np.ndarray
	band_offset: int
	e_dft_ev: np.ndarray
	eqp0_ev: np.ndarray
	eqp1_ev: np.ndarray
	kin_ion_diag_ev: np.ndarray
	hartree_diag_ev: np.ndarray          # post-seam: the V_H actually used
	sigma_x_diag_ev: np.ndarray
	sigma_c_at_dft_diag_ev: np.ndarray
	z_factor: np.ndarray | None
	hartree_rule: str                    # 'suppressed' | 'substituted' | 'as-given'
	implied_vxc_ev: np.ndarray | None
	nspin: int = 1

	def write(self, *, eqp0_path: str, eqp1_path: str) -> tuple[str, str]:
		"""Emit the exact-BGW-format eqp0.dat / eqp1.dat pair."""
		return write_eqp_bgw_pair(
			eqp0_path=eqp0_path, eqp1_path=eqp1_path,
			kpoints_irr_frac=self.kpoints_irr_frac,
			e_dft_ev=self.e_dft_ev,
			eqp0_ev=self.eqp0_ev, eqp1_ev=self.eqp1_ev,
			band_offset=self.band_offset, nspin=self.nspin,
		)


def assemble_eqp(
	*,
	kpoints_irr_frac: np.ndarray,
	band_offset: int,
	e_dft_ev: np.ndarray,                                  # (nk, nb)
	kin_ion_diag_ev: np.ndarray,                           # (nk, nb)
	hartree_diag_ev: np.ndarray,                           # (nk, nb) pre-seam
	sigma_x_diag_ev: np.ndarray,                           # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray | None = None,      # (nk, nb)
	# Optional: full ω-grid for the Z-factor (PPM modes only).
	# If None ⇒ Z=1 ⇒ eqp1 == eqp0 (BGW behaviour in static modes).
	sigma_c_omega_diag_ev: np.ndarray | None = None,       # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray | None = None,                # (n_omega,)
	e_dft_rel_ev: np.ndarray | None = None,                # (nk, nb)
	dE_ev: float = 0.5,
	nspin: int = 1,
	# The V_H seam (see resolve_hartree_diag_ev)
	hartree_source: str | None = None,
	kin_ion_has_hartree: bool = False,
	exact_hartree_diag_ev: np.ndarray | None = None,
	mean_field_gate: bool = True,
	print_fn=print,
) -> EqpAssembly:
	"""Assemble BGW QP energies from H₀ and Σ.  **One implementation.**

	Order of operations, and each step happens exactly once:

	1. the V_H seam (:func:`resolve_hartree_diag_ev`);
	2. the mean-field gate on the *resolved* H₀
	   (``gw.gw_output._warn_on_unphysical_h0`` — the source-aware
	   implied-V_xc check; warn-only, never raises);
	3. Σ_c at E_DFT and the central-difference Z-factor, when an ω-grid
	   is supplied (:func:`compute_z_factor_from_omega_grid`);
	4. the Newton update (:func:`compute_eqp_diag`).

	The gate lives HERE rather than in ``compute_eqp_diag`` (which must
	stay a silent pure function — pinned by
	``tests/test_sanity_gates.py::test_compute_eqp_diag_does_not_duplicate_the_mean_field_gate``)
	and no longer at the two call sites, so a single broken H₀ reports
	itself exactly once, in one wording, on both entry points.
	"""
	hartree_used, rule = resolve_hartree_diag_ev(
		hartree_diag_ev=hartree_diag_ev,
		hartree_source=hartree_source,
		kin_ion_has_hartree=kin_ion_has_hartree,
		exact_hartree_diag_ev=exact_hartree_diag_ev,
		print_fn=print_fn,
	)

	implied_vxc = None
	if mean_field_gate:
		implied_vxc = _warn_on_unphysical_h0(
			e_dft_ev=e_dft_ev,
			kin_ion_diag_ev=kin_ion_diag_ev,
			hartree_diag_ev=hartree_used,
			kin_ion_has_hartree=kin_ion_has_hartree,
			hartree_source=hartree_source,
			print_fn=print_fn,
		)
		# No second check here on purpose.  ``_warn_on_unphysical_h0``
		# emits its failure through ``common.sanity.warn``, so the
		# ``*** LORRAX SANITY FAILURE`` grep token and the strict-mode
		# raise both come from that ONE call — for the live driver and
		# for the post-hoc CLI alike.  O's policy kept, its duplicate
		# wording dropped.

	if sigma_c_omega_diag_ev is None:
		# Static mode: no ω-grid, Z = 1 trivially.
		if sigma_c_at_dft_diag_ev is None:
			raise ValueError(
				"assemble_eqp needs either sigma_c_at_dft_diag_ev (static "
				"modes) or sigma_c_omega_diag_ev + omega_rel_ev + "
				"e_dft_rel_ev (dynamic modes)")
		z_factor = None
		sigma_c_at_dft = sigma_c_at_dft_diag_ev
	else:
		if omega_rel_ev is None or e_dft_rel_ev is None:
			raise ValueError(
				"sigma_c_omega_diag_ev requires omega_rel_ev and e_dft_rel_ev")
		# Re-derive σ_c at E_DFT from the full ω-grid for self-consistency
		# with the Z-factor central difference.
		sigma_c_at_dft, z_factor = compute_z_factor_from_omega_grid(
			sigma_c_omega_diag_ev=sigma_c_omega_diag_ev,
			omega_rel_ev=omega_rel_ev,
			e_dft_rel_ev=e_dft_rel_ev,
			dE_ev=dE_ev,
		)

	eqp0_ev, eqp1_ev = compute_eqp_diag(
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=hartree_used,
		sigma_x_diag_ev=sigma_x_diag_ev,
		sigma_c_at_dft_diag_ev=sigma_c_at_dft,
		e_dft_ev=e_dft_ev,
		z_factor=z_factor,
	)
	return EqpAssembly(
		kpoints_irr_frac=np.asarray(kpoints_irr_frac, dtype=np.float64),
		band_offset=int(band_offset),
		e_dft_ev=np.asarray(e_dft_ev, dtype=np.float64),
		eqp0_ev=eqp0_ev, eqp1_ev=eqp1_ev,
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=hartree_used,
		sigma_x_diag_ev=sigma_x_diag_ev,
		sigma_c_at_dft_diag_ev=sigma_c_at_dft,
		z_factor=z_factor,
		hartree_rule=rule,
		implied_vxc_ev=implied_vxc,
		nspin=int(nspin),
	)


def _warn_on_unphysical_h0(**kwargs):
	"""The source-aware mean-field gate, single-sourced from the driver.

	Lives in ``gw.gw_output`` (with its window constants) because that is
	where the diagnosis text belongs; imported lazily here so this module
	stays importable on its own for the post-hoc CLI, exactly as
	:func:`_implied_vxc_window_ev` does.  If the driver is not importable
	(no jax on the host) the assembly falls back to the local
	warn-only bracket rather than skipping the check.
	"""
	try:
		from . import gw_output as _gwo
	except ImportError:
		_warn_on_unphysical_implied_vxc(
			e_dft_ev=kwargs["e_dft_ev"],
			kin_ion_diag_ev=kwargs["kin_ion_diag_ev"],
			hartree_diag_ev=kwargs["hartree_diag_ev"],
		)
		return None
	return _gwo._warn_on_unphysical_h0(**kwargs)


def write_eqp_bgw_pair(
	*,
	eqp0_path: str,
	eqp1_path: str,
	kpoints_irr_frac: np.ndarray,
	e_dft_ev: np.ndarray,
	eqp0_ev: np.ndarray,
	eqp1_ev: np.ndarray,
	band_offset: int,
	nspin: int = 1,
) -> tuple[str, str]:
	"""Write the BGW-format eqp0.dat + eqp1.dat pair from precomputed arrays.

	Both files share the same provenance header, k-point list, and
	``E_DFT`` column; only the ``E_QP`` column differs (zeroth-order
	vs. Z-linearized).
	"""
	write_bgw_eqp(eqp0_path, kpoints_irr_frac, e_dft_ev, eqp0_ev,
	              band_offset=band_offset, nspin=nspin)
	write_bgw_eqp(eqp1_path, kpoints_irr_frac, e_dft_ev, eqp1_ev,
	              band_offset=band_offset, nspin=nspin)
	return eqp0_path, eqp1_path


# ---------------------------------------------------------------------------
# In-memory entry point — used by the standard ``gw_output.write_results``
# path during a live gw_jax run (avoids re-reading sigma_mnk.h5 from disk).
# ---------------------------------------------------------------------------

def write_eqp_bgw_in_memory(
	*,
	eqp0_path: str,
	eqp1_path: str,
	kpoints_irr_frac: np.ndarray,
	band_offset: int,
	e_dft_ev: np.ndarray,                                  # (nk, nb)
	kin_ion_diag_ev: np.ndarray,                           # (nk, nb)
	hartree_diag_ev: np.ndarray,                           # (nk, nb)
	sigma_x_diag_ev: np.ndarray,                           # (nk, nb)
	sigma_c_at_dft_diag_ev: np.ndarray,                    # (nk, nb)
	# Optional: full ω-grid for the Z-factor (PPM modes only).
	# If None ⇒ Z=1 ⇒ eqp1 == eqp0 (BGW behavior in static modes).
	sigma_c_omega_diag_ev: np.ndarray | None = None,       # (n_omega, nk, nb)
	omega_rel_ev: np.ndarray | None = None,                # (n_omega,)
	e_dft_rel_ev: np.ndarray | None = None,                # (nk, nb), required if dynamic
	dE_ev: float = 0.5,
	nspin: int = 1,
	hartree_source: str | None = None,
	kin_ion_has_hartree: bool = False,
	exact_hartree_diag_ev: np.ndarray | None = None,
	print_fn=print,
) -> tuple[str, str]:
	"""Compute and write BGW-format ``eqp0.dat`` / ``eqp1.dat`` from in-memory arrays.

	Parallel of :func:`make_eqp_bgw` (the post-hoc CLI orchestrator) for the
	live gw_jax write path: the caller already has ``Σ_x``, ``V_H``,
	``kin_ion``, ``E_DFT`` in memory, so reloading them from disk would be
	wasteful.  **Both entry points are now the same two calls** —
	:func:`assemble_eqp` then :meth:`EqpAssembly.write` — so the V_H seam,
	the mean-field gate, the Z-factor and the formatter each exist once.

	``hartree_diag_ev`` is handed in PRE-seam (i.e. whatever the Σ side
	produced); the seam decides whether it is suppressed, substituted or
	used as given.
	"""
	return assemble_eqp(
		kpoints_irr_frac=kpoints_irr_frac,
		band_offset=band_offset,
		e_dft_ev=e_dft_ev,
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=hartree_diag_ev,
		sigma_x_diag_ev=sigma_x_diag_ev,
		sigma_c_at_dft_diag_ev=sigma_c_at_dft_diag_ev,
		sigma_c_omega_diag_ev=sigma_c_omega_diag_ev,
		omega_rel_ev=omega_rel_ev,
		e_dft_rel_ev=e_dft_rel_ev,
		dE_ev=dE_ev,
		nspin=nspin,
		hartree_source=hartree_source,
		kin_ion_has_hartree=kin_ion_has_hartree,
		exact_hartree_diag_ev=exact_hartree_diag_ev,
		print_fn=print_fn,
	).write(eqp0_path=eqp0_path, eqp1_path=eqp1_path)


# ---------------------------------------------------------------------------
# Orchestrator: read the run directory and emit eqp{0,1}.dat
# ---------------------------------------------------------------------------

def make_eqp_bgw(
	run_dir: str,
	*,
	wfn_path: Optional[str] = None,
	kin_ion_path: Optional[str] = None,
	sigma_mnk_path: Optional[str] = None,
	qp_rotations_path: Optional[str] = None,
	eqp0_out: str = "eqp0.dat",
	eqp1_out: str = "eqp1.dat",
	finite_difference_spacing_ev: float = 0.5,
) -> tuple[str, str]:
	"""Emit BGW-format ``eqp0.dat`` and ``eqp1.dat`` from a LORRAX gw_jax run.

	All file paths default to standard names inside ``run_dir``.  Returns
	``(eqp0_path, eqp1_path)``.
	"""
	wfn_path = wfn_path or os.path.join(run_dir, "WFN.h5")
	kin_ion_path = kin_ion_path or os.path.join(run_dir, "kin_ion.h5")
	sigma_mnk_path = sigma_mnk_path or os.path.join(run_dir, "sigma_mnk.h5")
	qp_rotations_path = qp_rotations_path or os.path.join(run_dir, "qp_wfn_rotations.h5")
	eqp0_path = (
		eqp0_out if os.path.isabs(eqp0_out) else os.path.join(run_dir, eqp0_out)
	)
	eqp1_path = (
		eqp1_out if os.path.isabs(eqp1_out) else os.path.join(run_dir, eqp1_out)
	)

	# IBZ k-points + per-state DFT energies (Ry → eV)
	with h5py.File(wfn_path, "r") as wfn:
		kpoints_irr = np.asarray(wfn["mf_header/kpoints/rk"])
		nspin = int(np.asarray(wfn["mf_header/kpoints/nspin"]))
		# energies: (nspin, nk, nbands_total) in Ry
		energies_ry = np.asarray(wfn["mf_header/kpoints/el"])
		ifmax = np.asarray(wfn["mf_header/kpoints/ifmax"])  # (nspin, nk) 1-based
	if nspin != 1:
		raise NotImplementedError("LORRAX runs at nspin=1; got nspin={}".format(nspin))

	nk_irr = kpoints_irr.shape[0]

	# IBZ → full-BZ index map; band_range
	with h5py.File(qp_rotations_path, "r") as qp:
		band_range = np.asarray(qp["band_range"], dtype=np.int64)
		kirr_to_kfull = np.asarray(qp["kirr_to_kfull"], dtype=np.int64)
	band_start, band_stop = int(band_range[0]), int(band_range[1])
	nb_window = band_stop - band_start
	if kirr_to_kfull.size != nk_irr:
		raise ValueError(
			f"kirr_to_kfull size {kirr_to_kfull.size} != IBZ kpts {nk_irr}"
		)

	# DFT energies on the IBZ wedge for the sigma window (eV)
	# energies_ry shape (nspin=1, nk_irr, nb_total); take spin 0.
	e_dft_ev = energies_ry[0, :, band_start:band_stop] * RYD_TO_EV
	if e_dft_ev.shape != (nk_irr, nb_window):
		raise ValueError(
			f"WFN energies shape {energies_ry.shape} inconsistent with "
			f"band_range {(band_start, band_stop)} on {nk_irr} IBZ kpts"
		)

	# Mid-gap Fermi level from the IBZ DFT energies (matches gw_jax convention)
	n_occ = int(np.max(ifmax[0]))                       # 1-based highest occ
	occ_idx_local = n_occ - 1 - band_start              # within the window
	if occ_idx_local < 0 or occ_idx_local + 1 >= nb_window:
		raise ValueError(
			"sigma window does not bracket VBM/CBM: band_range="
			f"[{band_start},{band_stop}), VBM index={n_occ - 1}"
		)
	vbm_ev = float(np.max(e_dft_ev[:, : occ_idx_local + 1]))
	cbm_ev = float(np.min(e_dft_ev[:, occ_idx_local + 1 :]))
	efermi_ev = 0.5 * (vbm_ev + cbm_ev)
	e_dft_rel_ev = e_dft_ev - efermi_ev

	# kin_ion (Ry → eV), pulled on the IBZ wedge directly
	with h5py.File(kin_ion_path, "r") as kih:
		kin_full = np.asarray(kih["kin_ion"])
	if kin_full.ndim != 3:
		raise ValueError(f"kin_ion dataset must be (nk, nb, nb); got {kin_full.shape}")
	kin_irr = kin_full[kirr_to_kfull, band_start:band_stop, band_start:band_stop]
	kin_ion_diag_ev = np.real(np.diagonal(kin_irr, axis1=1, axis2=2)) * RYD_TO_EV

	# sigma_mnk.h5: σ_x, σ_c(ω), V_H, ω axis (all already in eV, ω relative to E_F)
	with h5py.File(sigma_mnk_path, "r") as sf:
		omega_rel_ev = np.asarray(sf["omega_ev"], dtype=np.float64)
		sigma_x_full = np.asarray(sf["sigma_sx_kij_ev"])
		hartree_full = np.asarray(sf["hartree_kij_ev"])
		sigma_c_full = np.asarray(sf["sigma_c_kij_ev"])
	# Subset to IBZ wedge × sigma-window bands
	sigma_x_irr = sigma_x_full[kirr_to_kfull][:, band_start:band_stop, band_start:band_stop]
	hartree_irr = hartree_full[kirr_to_kfull][:, band_start:band_stop, band_start:band_stop]
	sigma_c_irr = sigma_c_full[:, kirr_to_kfull][:, :, band_start:band_stop, band_start:band_stop]

	sigma_x_diag = np.diagonal(sigma_x_irr, axis1=1, axis2=2)
	hartree_diag = np.diagonal(hartree_irr, axis1=1, axis2=2)
	sigma_c_omega_diag = np.diagonal(sigma_c_irr, axis1=2, axis2=3)  # (n_omega, nk, nb)

	# ── The V_H seam's ONE extra input on this path ───────────────────
	# ``gw.sigma_dispatch`` applies the source rule at the single point
	# V_H enters ``SigmaResult`` — but that covers the live driver only.
	# This CLI rebuilds eqp{0,1} straight from files, so it has to look
	# the source up itself and hand the seam its operand.  Everything
	# after that is :func:`assemble_eqp`, byte-for-byte the live path.
	#
	# The mixed case is the *normal* one here, not an edge case: a
	# ``sigma_mnk.h5`` written by an older run carries a non-zero ISDF
	# V_H, and pointing this CLI at a regenerated ``kin_ion.h5`` is
	# exactly how one re-derives QP energies without re-running Σ (Σ_xc
	# does not depend on V_H, so the rebuild is legitimate).
	# Double-counting ~500 eV of Hartree put the c606 sweep's QP gap at
	# −453 eV with rc=0 (job 7874840).
	#
	# Reading the attribute is the only supported discriminator — never
	# infer it from magnitudes (``file_io.kin_ion`` module docstring).
	# Imported lazily (as ``gw.sigma_dispatch`` does) so this module stays
	# importable without pulling in the jax-dependent file_io stack.
	from file_io.kin_ion import kin_ion_hartree_source, HARTREE_DATASET
	_src = kin_ion_hartree_source(kin_ion_path)
	vh_exact = None
	if _src == "stored":
		with h5py.File(kin_ion_path, "r") as kf:
			vh_full = np.asarray(kf[HARTREE_DATASET])
		if vh_full.shape[1] < band_stop:
			raise ValueError(
				f"{HARTREE_DATASET} covers {vh_full.shape[1]} bands but the "
				f"sigma window needs {band_stop}.")
		vh_irr = vh_full[kirr_to_kfull, band_start:band_stop,
		                 band_start:band_stop]
		vh_exact = np.real(np.diagonal(vh_irr, axis1=1, axis2=2)) * RYD_TO_EV

	# From here on: zero independent semantics.  Same assembly (seam +
	# mean-field gate + Z-factor + Newton update), same formatter, as
	# ``gw_output.write_results``.  This CLI's whole remaining job is
	# "load artifacts, then call these two".
	return assemble_eqp(
		kpoints_irr_frac=kpoints_irr,
		band_offset=band_start,
		e_dft_ev=e_dft_ev,
		kin_ion_diag_ev=kin_ion_diag_ev,
		hartree_diag_ev=np.real(hartree_diag),
		sigma_x_diag_ev=np.real(sigma_x_diag),
		sigma_c_omega_diag_ev=sigma_c_omega_diag,
		omega_rel_ev=omega_rel_ev,
		e_dft_rel_ev=e_dft_rel_ev,
		dE_ev=finite_difference_spacing_ev,
		nspin=1,
		hartree_source=_src,
		exact_hartree_diag_ev=vh_exact,
	).write(eqp0_path=eqp0_path, eqp1_path=eqp1_path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
	p = argparse.ArgumentParser(allow_abbrev=False,
		prog="python -m gw.eqp_bgw",
		description="Reproduce BGW eqp0.dat / eqp1.dat from a LORRAX gw_jax run.",
	)
	p.add_argument("run_dir", help="Run directory containing WFN.h5, kin_ion.h5, sigma_mnk.h5, qp_wfn_rotations.h5")
	p.add_argument("--wfn", default=None, help="Path to WFN.h5 (default: <run_dir>/WFN.h5)")
	p.add_argument("--kin-ion", default=None, help="Path to kin_ion.h5")
	p.add_argument("--sigma-mnk", default=None, help="Path to sigma_mnk.h5")
	p.add_argument("--qp-rotations", default=None, help="Path to qp_wfn_rotations.h5")
	p.add_argument("--eqp0", default="eqp0.dat", help="Output eqp0 filename (relative to run_dir unless absolute)")
	p.add_argument("--eqp1", default="eqp1.dat", help="Output eqp1 filename (relative to run_dir unless absolute)")
	p.add_argument(
		"--finite-difference-spacing",
		type=float, default=0.5,
		help="dE (eV) for the Z-factor central difference (BGW default 0.5)",
	)
	return p


def main(argv: Optional[list[str]] = None) -> int:
	args = _build_parser().parse_args(argv)
	eqp0_path, eqp1_path = make_eqp_bgw(
		args.run_dir,
		wfn_path=args.wfn,
		kin_ion_path=args.kin_ion,
		sigma_mnk_path=args.sigma_mnk,
		qp_rotations_path=args.qp_rotations,
		eqp0_out=args.eqp0,
		eqp1_out=args.eqp1,
		finite_difference_spacing_ev=args.finite_difference_spacing,
	)
	print(f"wrote: {eqp0_path}")
	print(f"wrote: {eqp1_path}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
